"""Pyramid combine layer for Player A.

This module defines :class:`~Q_Sea_Battle.PyrCombineLayerA`, a Keras layer used
to compute the next field state at each pyramid level.

The Step 1 implementation encodes the teacher rule from the Pyr dataset spec:
combine the *even* bits of the current field with the PR-assisted outcome.

Author: Rob Hendriks (spec)
Maintainer: autogenerated by ChatGPT
Version: 0.1
"""

# Note: sr_* naming is kept for backward compatibility: SR = shared resource.

from __future__ import annotations

from typing import Optional

import tensorflow as tf


class PyrCombineLayerA(tf.keras.layers.Layer):
    """Compute Player A's next field state for a pyramid level.

    Purpose:
        Given a current binary field state ``F^ℓ`` of length ``L`` (even),
        and a PR-assisted outcome ``S_A^ℓ`` of length ``L/2``, compute:

            F^{ℓ+1}[i] = F^ℓ[2*i] XOR S_A^ℓ[i].

        This layer is intentionally *non-trainable* for Step 1: it encodes the
        reference/teacher rule used by the imitation dataset generator.

    Args:
        name: Optional Keras layer name.

    Call Args:
        field_batch: Tensor of shape ``(B, L)`` with values in ``{0, 1}``.
        sr_outcome_batch: Tensor of shape ``(B, L/2)`` with values in ``{0, 1}``, representing the PR-assisted outcome..

    Returns:
        Tensor of shape ``(B, L/2)`` with values in ``{0, 1}`` (dtype float32).
    """

    def __init__(self, name: Optional[str] = None) -> None:
        super().__init__(name=name, trainable=False)

    def call(self, field_batch: tf.Tensor, sr_outcome_batch: tf.Tensor) -> tf.Tensor:
        """Combine current field with PR-assisted outcome.

        Args:
            field_batch: Tensor of shape ``(B, L)`` with values in ``{0, 1}``.
            sr_outcome_batch: Tensor of shape ``(B, L/2)`` with values in ``{0, 1}``, representing the PR-assisted outcome..

        Returns:
            Tensor of shape ``(B, L/2)`` in ``{0, 1}``.
        """
        field = tf.convert_to_tensor(field_batch, dtype=tf.float32)
        sr = tf.convert_to_tensor(sr_outcome_batch, dtype=tf.float32)

        L = tf.shape(field)[-1]
        tf.debugging.assert_equal(L % 2, 0, message="Active length L must be even.")
        # Even positions: 0,2,4,...
        even = field[..., ::2]
        tf.debugging.assert_equal(
            tf.shape(even)[-1],
            tf.shape(sr)[-1],
            message="sr_outcome length must equal L/2.",
        )
        next_field = tf.math.floormod(even + sr, 2.0)
        return next_field
