"""Pyramid (Pyr) architecture layers for QSeaBattle.

This package segment contains the non-trainable Step-1 pyramid layer primitives:
measurement and combine layers for Player A and Player B.

They implement the teacher rules used by the pyramid imitation-learning dataset
specification.

Author: Rob Hendriks (spec)
Maintainer: autogenerated by ChatGPT
Version: 0.1
"""

from .pyr_measurement_layer_a import PyrMeasurementLayerA
from .pyr_measurement_layer_b import PyrMeasurementLayerB
from .pyr_combine_layer_a import PyrCombineLayerA
from .pyr_combine_layer_b import PyrCombineLayerB

__all__ = [
    "PyrMeasurementLayerA",
    "PyrMeasurementLayerB",
    "PyrCombineLayerA",
    "PyrCombineLayerB",
]
