"""Pyramid measurement layer for Player A.

This module defines :class:`~Q_Sea_Battle.PyrMeasurementLayerA`, a Keras layer
used in the Pyramid (Pyr) assisted architecture.

In the Pyr architecture, the active state length is halved at each pyramid
level. This layer implements the *teacher target* measurement rule described
in the QSeaBattle specification: pairwise XOR of the current field state.

Author: Rob Hendriks (spec)
Maintainer: autogenerated by ChatGPT
Version: 0.1
"""

from __future__ import annotations

from typing import Optional

import tensorflow as tf


class PyrMeasurementLayerA(tf.keras.layers.Layer):
    """Compute Player A's per-level measurement vector.

    Purpose:
        Given a binary field state ``F^ℓ`` of length ``L``, produce the
        measurement vector ``M_A^ℓ`` of length ``L/2`` via pairwise XOR:

            M_A^ℓ[i] = F^ℓ[2*i] XOR F^ℓ[2*i + 1].

        This layer is intentionally *non-trainable* for Step 1: it encodes
        the reference/teacher rule so dataset generation and early integration
        tests can be validated.

    Args:
        name: Optional Keras layer name.

    Call Args:
        field_batch: Tensor of shape ``(B, L)`` with values in ``{0, 1}``.
            ``L`` must be even.

    Returns:
        Tensor of shape ``(B, L/2)`` with values in ``{0, 1}`` (dtype float32).
    """

    def __init__(self, name: Optional[str] = None) -> None:
        super().__init__(name=name, trainable=False)

    def call(self, field_batch: tf.Tensor) -> tf.Tensor:
        """Compute pairwise XOR measurements.

        Args:
            field_batch: Tensor of shape ``(B, L)`` with values in ``{0, 1}``.

        Returns:
            Tensor of shape ``(B, L/2)`` in ``{0, 1}``.
        """
        x = tf.convert_to_tensor(field_batch, dtype=tf.float32)
        # Validate even length at runtime (defensive).
        L = tf.shape(x)[-1]
        tf.debugging.assert_equal(L % 2, 0, message="Active length L must be even.")
        # Reshape into pairs: (..., L/2, 2)
        pairs = tf.reshape(x, tf.concat([tf.shape(x)[:-1], [L // 2, 2]], axis=0))
        even = pairs[..., 0]
        odd = pairs[..., 1]
        # XOR over {0,1}: (a + b) mod 2
        meas = tf.math.floormod(even + odd, 2.0)
        return meas
