#!/usr/bin/env python3
"""
Polish QSeaBattle docstrings and comments with an LLM.

Conservative guarantees:
- Processes one Python file at a time.
- Uses Google-style docstrings.
- Allows changes only to comments/docstrings.
- Rejects any candidate whose executable AST differs.
- Saves rejected candidates and prints their diff for diagnosis.
- Supports path exclusions such as temporary archive folders.
- Adds a human author header without AI attribution.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from openai import OpenAI


SYSTEM_PROMPT = r"""
You are reviewing one Python source file from the public QSeaBattle repository.

This is a DOCUMENTATION-ONLY pass.

Improve only:
- module docstrings
- public class docstrings
- public method docstrings
- public function docstrings
- useful inline comments
- spelling, grammar, terminology, and clarity in comments/docstrings

STYLE
- Use Google-style docstrings.
- Keep prose concise and professional.
- Explain non-obvious physics, mathematics, tensor semantics, and protocol logic.
- Do not comment obvious Python syntax.
- Preserve useful implementation comments.
- Public functions/classes/methods should normally have docstrings.
- Private helpers should have docstrings when their purpose or contract is not obvious.
- Document Args, Returns, Raises, and Attributes only when applicable.
- Include tensor/array dtype and shape when knowable from code.
- Do not invent guarantees, shapes, exceptions, or semantics not supported by source.

PROJECT TERMINOLOGY
- Prefer `p_rule`; do not introduce `p_high`.
- Use "shared resource" or "SR" consistently with the implementation.
- Use "PR-assisted" where the code specifically implements the PR-assisted resource.
- Use `replay` and `stochastic` for current SR modes.
- Game/player boundaries use bits.
- Trainable internal model interfaces use logits.
- Logical bit values represented as logits are determined by logit sign.
- Preserve compatibility/deprecation notes when they are still true.

AUTHORSHIP / ATTRIBUTION
- Do NOT mention ChatGPT, OpenAI, AI, LLMs, prompts, generated code, or assisted authorship.
- Do NOT add "created by", "generated by", or similar provenance statements.
- Do NOT change existing human author attribution.
- Author metadata is handled outside this editing task.

HARD CONSTRAINTS
- Do NOT change imports.
- Do NOT rename variables, functions, methods, classes, constants, or modules.
- Do NOT change signatures or annotations.
- Do NOT reorder executable statements.
- Do NOT change expressions, control flow, algorithms, constants, defaults, tensor shapes, return values, or API behavior.
- Do NOT add/remove decorators.
- Do NOT add/remove compatibility aliases.
- Do NOT add executable metadata assignments such as __author__ or __version__.
- Comments and docstrings may be added, removed, or rewritten.
- Blank lines may be adjusted only where needed for documentation.

If documentation appears inconsistent with executable code:
- make docs match code when unambiguous;
- otherwise leave a concise `TODO(review): ...` comment;
- never fix executable code.

OUTPUT
Return ONLY the complete revised Python file.
No Markdown fences. No explanation.
""".strip()


USER_PROMPT = r"""
Review this QSeaBattle Python module.

Module path:
{module_path}

Python source:
<<<PYTHON
{source}
PYTHON>>>

Return the complete revised Python source only.
""".strip()


@dataclass(frozen=True)
class ReviewResult:
    source_path: Path
    output_path: Path
    changed: bool
    diff_lines: int


def iter_python_files(src: Path) -> Iterable[Path]:
    yield from sorted(p for p in src.rglob("*.py") if "__pycache__" not in p.parts)


def _strip_docstrings(tree: ast.AST) -> ast.AST:
    class Strip(ast.NodeTransformer):
        @staticmethod
        def strip_first(body):
            if (
                body
                and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)
            ):
                return body[1:]
            return body

        def visit_Module(self, node):
            self.generic_visit(node)
            node.body = self.strip_first(node.body)
            return node

        def visit_ClassDef(self, node):
            self.generic_visit(node)
            node.body = self.strip_first(node.body)
            return node

        def visit_FunctionDef(self, node):
            self.generic_visit(node)
            node.body = self.strip_first(node.body)
            return node

        def visit_AsyncFunctionDef(self, node):
            self.generic_visit(node)
            node.body = self.strip_first(node.body)
            return node

    return Strip().visit(tree)


def executable_ast_dump(source: str) -> str:
    tree = ast.parse(source)
    tree = _strip_docstrings(tree)
    ast.fix_missing_locations(tree)
    return ast.dump(tree, annotate_fields=True, include_attributes=False)


def assert_documentation_only(original: str, candidate: str, path: Path) -> None:
    try:
        original_ast = executable_ast_dump(original)
        candidate_ast = executable_ast_dump(candidate)
    except SyntaxError as exc:
        raise RuntimeError(f"Python parse error for {path}: {exc}") from exc

    if original_ast != candidate_ast:
        raise RuntimeError(
            f"Rejected {path}: executable AST changed. "
            "Only comments/docstrings are allowed to change."
        )


AI_PATTERNS = [
    re.compile(r"\bchatgpt\b", re.I),
    re.compile(r"\bopenai\b", re.I),
    re.compile(r"\bai[- ]generated\b", re.I),
    re.compile(r"\bllm[- ]generated\b", re.I),
    re.compile(r"\bcreated\s+by\s+ai\b", re.I),
    re.compile(r"\bgenerated\s+by\s+ai\b", re.I),
]


def assert_no_ai_attribution(candidate: str, path: Path) -> None:
    for pattern in AI_PATTERNS:
        if pattern.search(candidate):
            raise RuntimeError(
                f"Rejected {path}: prohibited AI attribution matched {pattern.pattern!r}"
            )


def normalize_author_header(source: str, author: str) -> str:
    lines = source.splitlines()
    author_re = re.compile(r"^\s*#\s*Author\s*:\s*.*$", re.I)
    lines = [line for line in lines if not author_re.match(line)]

    insert_at = 0
    if lines and lines[0].startswith("#!"):
        insert_at = 1

    encoding_re = re.compile(r"^#.*coding[:=]\s*[-\w.]+")
    if insert_at < len(lines) and encoding_re.match(lines[insert_at]):
        insert_at += 1

    lines.insert(insert_at, f"# Author: {author}")
    if insert_at + 1 < len(lines) and lines[insert_at + 1].strip():
        lines.insert(insert_at + 1, "")

    return "\n".join(lines) + ("\n" if source.endswith("\n") else "")


def remove_outer_fence(text: str) -> str:
    s = text.strip()
    if s.startswith("```python") and s.endswith("```"):
        return s[len("```python"):-3].strip("\n")
    if s.startswith("```") and s.endswith("```"):
        return s[3:-3].strip("\n")
    return s


def count_diff_lines(a: str, b: str) -> int:
    diff = difflib.unified_diff(a.splitlines(), b.splitlines(), lineterm="")
    return sum(
        1 for line in diff
        if (line.startswith("+") or line.startswith("-"))
        and not line.startswith("+++")
        and not line.startswith("---")
    )



def save_rejected_candidate(
    *,
    original: str,
    candidate: str,
    src_path: Path,
    src_root: Path,
    rejected_root: Path,
) -> Path:
    """Save an unsafe LLM candidate and print its unified diff."""
    rel = src_path.relative_to(src_root)
    debug_path = rejected_root / rel
    debug_path.parent.mkdir(parents=True, exist_ok=True)
    debug_path.write_text(candidate, encoding="utf-8")

    print(f"    SAVED REJECTED CANDIDATE: {debug_path}")
    print(f"    --- DIFF FOR REJECTED CANDIDATE: {rel} ---")
    for line in difflib.unified_diff(
        original.splitlines(),
        candidate.splitlines(),
        fromfile=str(src_path),
        tofile=str(debug_path),
        lineterm="",
    ):
        print(line)

    return debug_path

def review_file(
    client: OpenAI,
    model: str,
    src_path: Path,
    src_root: Path,
    out_path: Path,
    author: str,
    show_diff: bool,
    rejected_root: Path,
) -> ReviewResult:
    original = src_path.read_text(encoding="utf-8")
    module_path = ".".join(src_path.relative_to(src_root).with_suffix("").parts)

    response = client.responses.create(
        model=model,
        instructions=SYSTEM_PROMPT,
        input=USER_PROMPT.format(module_path=module_path, source=original),
    )

    candidate = remove_outer_fence(response.output_text)

    try:
        assert_no_ai_attribution(candidate, src_path)
        assert_documentation_only(original, candidate, src_path)
    except Exception:
        save_rejected_candidate(
            original=original,
            candidate=candidate,
            src_path=src_path,
            src_root=src_root,
            rejected_root=rejected_root,
        )
        raise

    candidate = normalize_author_header(candidate, author)

    try:
        assert_documentation_only(original, candidate, src_path)
    except Exception:
        save_rejected_candidate(
            original=original,
            candidate=candidate,
            src_path=src_path,
            src_root=src_root,
            rejected_root=rejected_root,
        )
        raise

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(candidate, encoding="utf-8")

    if show_diff and candidate != original:
        for line in difflib.unified_diff(
            original.splitlines(),
            candidate.splitlines(),
            fromfile=str(src_path),
            tofile=str(out_path),
            lineterm="",
        ):
            print(line)

    return ReviewResult(
        source_path=src_path,
        output_path=out_path,
        changed=(candidate != original),
        diff_lines=count_diff_lines(original, candidate),
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", type=Path, default=Path("src/Q_Sea_Battle"))
    ap.add_argument("--out", type=Path, default=Path("src_reviewed/Q_Sea_Battle"))
    ap.add_argument("--in-place", action="store_true")
    ap.add_argument("--author", default="Rob Hendriks")
    ap.add_argument("--model", default="gpt-5.2")
    ap.add_argument("--overwrite", action="store_true")
    ap.add_argument("--show-diff", action="store_true")
    ap.add_argument("--only", default="", help="Optional path substring filter")
    ap.add_argument(
        "--exclude",
        action="append",
        default=[],
        help="Exclude paths containing this substring; may be repeated.",
    )
    ap.add_argument(
        "--rejected-dir",
        type=Path,
        default=Path("rejected_candidates"),
        help="Folder for LLM candidates rejected by safety checks.",
    )
    args = ap.parse_args()

    src_root = args.src.resolve()
    if not src_root.is_dir():
        raise SystemExit(f"Source directory not found: {src_root}")

    if not os.getenv("OPENAI_API_KEY"):
        raise SystemExit("OPENAI_API_KEY is not set.")

    files = list(iter_python_files(src_root))
    if args.only:
        files = [p for p in files if args.only.lower() in str(p).lower()]

    if args.exclude:
        exclude_terms = [term.lower() for term in args.exclude]
        files = [
            p for p in files
            if not any(term in str(p).lower() for term in exclude_terms)
        ]

    if not files:
        raise SystemExit("No matching Python files found.")

    client = OpenAI()

    changed = skipped = failed = 0
    print(f"Reviewing {len(files)} files")
    print("Convention: Google-style docstrings")
    print(f"Author: {args.author}")
    print(f"Model: {args.model}\n")

    for i, src_path in enumerate(files, 1):
        rel = src_path.relative_to(src_root)
        out_path = src_path if args.in_place else args.out.resolve() / rel

        if out_path.exists() and not args.overwrite and not args.in_place:
            print(f"[{i:03d}/{len(files):03d}] SKIP: {rel}")
            skipped += 1
            continue

        print(f"[{i:03d}/{len(files):03d}] REVIEW: {rel}")
        try:
            result = review_file(
                client,
                args.model,
                src_path,
                src_root,
                out_path,
                args.author,
                args.show_diff,
                args.rejected_dir.resolve(),
            )
            if result.changed:
                changed += 1
                print(f"    WROTE: {out_path} ({result.diff_lines} diff lines, AST safe)")
            else:
                print("    unchanged")
        except Exception as exc:
            failed += 1
            print(f"    REJECTED/FAILED: {exc}")

    print("\nSummary")
    print(f"  reviewed: {len(files)}")
    print(f"  changed : {changed}")
    print(f"  skipped : {skipped}")
    print(f"  failed  : {failed}")

    if failed:
        raise SystemExit(1)


if __name__ == "__main__":
    main()